//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionArticles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autocar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autocar()
        {
            this.Navettes = new HashSet<Navette>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_societe { get; set; }
        public string maricule { get; set; }
        public Nullable<int> nombre_places { get; set; }
    
        public virtual SocietéTransport SocietéTransport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Navette> Navettes { get; set; }
    }
}
