//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionArticles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public Nullable<int> id_navette { get; set; }
        public Nullable<int> id_user { get; set; }
        public int id { get; set; }
    
        public virtual Navette Navette { get; set; }
        public virtual Utilissateur Utilissateur { get; set; }
    }
}
