//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionArticles.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionAutocarsEntities : DbContext
    {
        public GestionAutocarsEntities()
            : base("name=GestionAutocarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autocar> Autocars { get; set; }
        public virtual DbSet<Navette> Navettes { get; set; }
        public virtual DbSet<SocietéTransport> SocietéTransport { get; set; }
        public virtual DbSet<Utilissateur> Utilissateurs { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<Abonnement> Abonnements { get; set; }
        public virtual DbSet<Demande> Demandes { get; set; }
    }
}
