//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionArticles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Navette()
        {
            this.Utilissateurs = new HashSet<Utilissateur>();
            this.Abonnements = new HashSet<Abonnement>();
            this.Demandes = new HashSet<Demande>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_ville_depart { get; set; }
        public Nullable<int> id_ville_arriver { get; set; }
        public Nullable<System.DateTime> heur_depart { get; set; }
        public Nullable<System.DateTime> heur_arriver { get; set; }
        public Nullable<bool> disponible { get; set; }
        public Nullable<bool> demande { get; set; }
        public Nullable<int> id_car { get; set; }
    
        public virtual Autocar Autocar { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilissateur> Utilissateurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demande> Demandes { get; set; }
    }
}
