//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionArticles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilissateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilissateur()
        {
            this.Abonnements = new HashSet<Abonnement>();
            this.Demandes = new HashSet<Demande>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_Navette { get; set; }
        public string nom_complet { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string login { get; set; }
        public string mdp { get; set; }
    
        public virtual Navette Navette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demande> Demandes { get; set; }
    }
}
